sudo: required
language: cpp

matrix:
  include:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
  - env: GCC_VERSION="4.9"
    os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        packages:
        - gcc-4.9
        - g++-4.9
        sources:
        - ubuntu-toolchain-r-test
        
  - env: CLANG_VERSION="3.7"
    os: linux
    dist: trusty
    compiler: clang
    addons:
      apt:
        packages:
        - clang-3.7
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        
  - env: GCC_VERSION="4.9"
    os: osx
    compiler: gcc
    
  - env: CLANG_VERSION="3.7"
    os: osx
    compiler: clang

# Install dependencies
install:

  - export ROOT_PATH=`pwd`/../;
  - export CHECKOUT_PATH=`pwd`;
  - echo "ROOT_PATH= $ROOT_PATH"
  - echo "CHECKOUT_PATH= $CHECKOUT_PATH"
  
  - chmod +x $CHECKOUT_PATH/travis/install_${TRAVIS_OS_NAME}.sh
  - . $CHECKOUT_PATH/travis/install_${TRAVIS_OS_NAME}.sh
 

script:
  - chmod +x $CHECKOUT_PATH/travis/build.sh
  - . $CHECKOUT_PATH/travis/build.sh

after_success:
  - cd $CHECKOUT_PATH
  - git reset --hard HEAD # Discard build artifacts
  - git clean -df # Discard build artifacts
  #- bii init -l
  #- bii user $BIICODE_USER -p $BIICODE_PASSWORD
  #- if [ -n "$BIICODE_PASSWORD" ]; then bii publish -r; fi

notifications:
  email: false
